### ISSUE TITLE
File watching not enabled for the environment panel

### ISSUE THREAD

**Issue by cwebster-99** [microsoft/vscode-python-environments#21]
Deleting an environment within the UI refreshes automatically but deleting in the file explorer causes an error on refresh / doesn't auto refresh in the environments view
![Image](https://github.com/user-attachments/assets/4e4706a1-1fd1-4731-acba-954018b7ee70)

**Comment by cwebster-99** [comment]
~Testing this on the new vsix and it correctly updates the environment manager list but it still has the deleted environment selected on the Python project fold. I think it should switch it back to the system default~

jk it was too fast and I didnt realize it was actually working

**Comment by karthiknadig** [comment]
It should switch back to system default. I see this on my machine. There could be a bug.
