### ISSUE TITLE
Show "open workspace" notification when selecting "click to create" venv when not in a workspace

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-python-environments#32]
When we're in single file/no workspace mode, it'd be nice to show the "open workspace" notification, or maybe just hide the "click to create" wording from the venv env manager, since it won't do anything on that scenario:

![Image](https://github.com/user-attachments/assets/ed1a5ee8-de43-4538-a9d7-8a390ec2b46f)

**Comment by karthiknadig** [comment]
This is what you should have seen:
![Image](https://github.com/user-attachments/assets/9f6fb6b7-058c-4e6c-b992-2d90d4d73652)
