### ISSUE TITLE
Deleting an environment and creating a new one with the same name shows "env already exists"

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-python-environments#33]
To reproduce:
- Create a venv, e.g. called `.venv310`
- Select it for your project 
- Delete the environment 
- Refresh the env manager view to confirm it is gone from there too
- Create a new environment from the env manager view, with the same version and name as the one before
I'm seeing this:
![Image](https://github.com/user-attachments/assets/d8c2c308-8cb0-4e94-937b-e96565b9f72d)

**Comment by karthiknadig** [comment]
This check actually looks for the folder. Sometimes the venv might be deleted but the folder still remains. Can you verify that the folder was actually removed?

**Comment by luabud** [comment]
the folder had been removed, but I can no longer reproduce this, so I'm closing it.
