### ISSUE TITLE
Error refreshing packages after trying to remove packages

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-python-environments#45]
Testing microsoft/vscode-python#24503

- Open a folder 'python-env-test' that contains a Python project
- Run the 'View: Show Python Environments'
- In the 'Environment managers' view, select 'Python 2.7.18' from the Global list
- Click on the 'Install Or Remove Packages' icons
- In the quick pick select 'Uninstall'

Error dialog 'Error refreshing packages'

Console says:
`Error refreshing packages Failed to run python -m pip list`

**Comment by karthiknadig** [comment]
Unfortunately, this is due to python 2.7 not being supported. 

Duplicate of https://github.com/microsoft/vscode-python-environments/issues/67
