### ISSUE TITLE
Can create environment from Python 2.7.18

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-python-environments#47]
Testing #24503

- Open a folder 'python-env-test' that contains a Python project
- Run the 'View: Show Python Environments' 
- In the Environment Managers view, run the 'Create Environment' button. Select a Python 2.7.18, use `.venv4` as name
Fails.

![Image](https://github.com/user-attachments/assets/711d78ee-a12f-4c9b-a6ba-221154565abd)

**Comment by karthiknadig** [comment]
@aeschli Python 2.7 is not supported. It has been deprecated for over 4 years now. We don;t test or check versions any more for python 2.7 because most machines don't have it. 

I will create an issue to filter out 2.7 .

**Comment by karthiknadig** [comment]
Duplicate of https://github.com/microsoft/vscode-python-environments/issues/67
