### ISSUE TITLE
[notice] under my installed packages

### ISSUE THREAD

**Issue by kristapratico** [microsoft/vscode-python-environments#83]
Python Environments version: 0.1.2024121005

I'm not sure what the highlighted notice is that's showing up under my installed packages for the venv:

![Image](https://github.com/user-attachments/assets/3837b981-d222-409a-8339-b96e0bfaa34a)

Should this be here?

**Comment by karthiknadig** [comment]
@kristapratico can you send me the output of `python -m pip list` for that environment.

**Comment by karthiknadig** [comment]
It is this thing:
![Image](https://github.com/user-attachments/assets/6933ac96-41d7-4c8a-9ccc-358e5c2d9fcf)

**Comment by kristapratico** [comment]
> It is this thing: ![Image](https://github.com/user-attachments/assets/6933ac96-41d7-4c8a-9ccc-358e5c2d9fcf)

Oh wow I never would have guessed that's where it was coming from! Thanks!
