### ISSUE TITLE
Error running command python-envs.refreshallmanagers: command 'python-envs.refreshallmanagers' not found

### ISSUE THREAD

**Issue by JCTrapero** [microsoft/vscode-python-environments#86]
Hi,
Sorry in advance for my perhaps basic lack of knowledge about how this extension works.
I just installed it, and when trying to load environment managers, it shows this error:

**"Error running command python-envs.refreshallmanagers: command 'python-envs.refreshallmanagers' not found"**

Value settings are default.

See below an screen capture of VS Code

![Image](https://github.com/user-attachments/assets/735cd58d-01f0-4bd7-95be-5ac246525399)

Any idea?
Thanks a lot!

**Comment by karthiknadig** [comment]
@JCTrapero Do you have a python file open in the editor? If yes, then do you see any errors reported in Output > Python Environments or in Help > Toggle Developer tools.

**Comment by JCTrapero** [comment]
Hi, @karthiknadig 

Toggle Developer tools capture

![Image](https://github.com/user-attachments/assets/b2118404-1691-499d-ad76-8cb498fad3c5)

My Python extension is V2024.22, but VS Code says that it's up to date

**Comment by JCTrapero** [comment]
Ah, Python version is 3.12.7

**Comment by karthiknadig** [comment]
@JCTrapero Please install pre-release version of the python extension. This is the relevant error:
![Image](https://github.com/user-attachments/assets/2f6a5c6b-b136-4ca7-8109-367042d29ca1)

From the extensions view you should be able to install pre-release python:
![Image](https://github.com/user-attachments/assets/690b2490-1c7e-4f29-8888-e01265d20096)

**Comment by karthiknadig** [comment]
There should be a button in the extensions view to switch to pre-release,:
![Image](https://github.com/user-attachments/assets/f7784576-2d1f-4717-adac-19f5359c7692)

**Comment by JCTrapero** [comment]
It's works!

Thanks
