### ISSUE TITLE
Env Manager maps package manager name to vscode-python extension for `preferredPackageManagerId`

### ISSUE THREAD

**Issue by jjjermiah** [microsoft/vscode-python-environments#96]
I might just be confused or possibly having unimplemented methods in my `PackageManager` implementation is the culprit here but wanted to drop this:

<details><summary>Scenario 1</summary>

  ```ts
  export class PixiPackageManager implements PackageManager {
    readonly name = "pixi";
    ...
  ```

and 

```ts
  export class PixiEnvironmentManager implements EnvironmentManager {
    name: string = "Pixi";
    displayName: string = "Pixi Environment Manager";
    preferredPackageManagerId: string = "jjjermiah.pixi-vscode2:pixi";
     ...
```

results in :
<img width="352" alt="Image" src="https://github.com/user-attachments/assets/d680f54d-a298-425d-85d4-e230a74e913e" />

- I also tried setting `preferredPackageManagerId="pixi"`, which didnt work either
</details> 

<details><summary>Scenario 2</summary>

to do some investigation I changed the name to `conda` and preferred id to `conda`

  ```ts
  export class PixiPackageManager implements PackageManager {
    readonly name = "conda";
    ...
  ```

and 

```ts
  export class PixiEnvironmentManager implements EnvironmentManager {
    name: string = "Pixi";
    displayName: string = "Pixi Environment Manager";
    preferredPackageManagerId: string = "jjjermiah.pixi-vscode2:conda";
     ...
```
<img width="377" alt="Image" src="https://github.com/user-attachments/assets/d4bf9eed-44ac-403f-ba49-dd15ef5a9186" />

</details> 

Based on the error in scenario 2, this lead me to trying:

<details><summary>Scenario 3</summary>

setting the packagemanager name to `pixi` but calling the preferredId as the vscode-python extension prefix

  ```ts
  export class PixiPackageManager implements PackageManager {
    readonly name = "pixi";
    readonly displayName = "Pixi DisplayName";
    ...
  ```

and 

```ts
  export class PixiEnvironmentManager implements EnvironmentManager {
    name: string = "Pixi";
    displayName: string = "Pixi Environment Manager";
    preferredPackageManagerId: string = "ms-python.python:pixi";
     ...
```
which works:

<img width="394" alt="Image" src="https://github.com/user-attachments/assets/27bf9fec-8505-4471-8d21-44b67657d9da" />

additionally it took a while to understand that the `preferredId` composed of the `<extension-publisher>.<extension-name>:<packageManager.name>` so perhaps that could be clarified? 

alternative solution would be to let developers provide their own `id` of the package manager during `register` step

</details> 

I think I traced it down to these:

https://github.com/microsoft/vscode-python-environments/blob/a2bfe2bb4cb83d28185e2613de40deb729edd1d9/src/features/envManagers.ts#L113-L121 

https://github.com/microsoft/vscode-python-environments/blob/a2bfe2bb4cb83d28185e2613de40deb729edd1d9/src/common/extensions.apis.ts#L1-L24

**Comment by karthiknadig** [comment]
@jjjermiah Would you mind sharing your branch, I can see what is going on. My assumption is that since you might be using development path, the `id` calculation is failing, and you also found a bug with it. 

I will update the docs to ensure that the `id` spec has the right details.

**Comment by jjjermiah** [comment]
I've been experimenting around in a sandbox repo: https://github.com/jjjermiah/pixi-vscode2 from scratch

**Comment by karthiknadig** [comment]
@jjjermiah I have a fix for this, you can try this build:
https://github.com/microsoft/vscode-python-environments/actions/runs/12400930049/artifacts/2339897806

Note that you may be, since this is a GH Action build, you may not be able to install this for your tests. But it should generate the right ids, for you, while debugging your extension.

**Comment by karthiknadig** [comment]
Try with the latest pre-release. It should work better.

**Comment by jjjermiah** [comment]
works great thank you!
