### ISSUE TITLE
Error when click on "Add python project" button

### ISSUE THREAD

**Issue by Akopov4** [microsoft/vscode-python-environments#98]
Type: <b>Bug</b>

When I click on "Add python project" button  , i see an error: Error running command python-envs.addPythonProject: command 'python-envs.addPythonProject' not found. This is likely caused by the extension that contributes python-envs.addPythonProject.

Extension version: 0.1.2024121902
VS Code version: Code 1.96.1 (42b266171e51a016313f47d0c48aca9295b9cbb2, 2024-12-17T17:50:05.206Z)
OS version: Linux x64 6.8.0-51-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2899)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 2, 1|
|Memory (System)|11.56GB (2.01GB free)|
|Process Argv|--crash-reporter-id cecfc8a1-377e-4a68-a073-92185890f5af|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by karthiknadig** [comment]
This can happen if the extension is not activated. Please open a Python file, that should activate it. Also, please share logs from Output > Python Environments and from Developer tools console ( Help > Toggle Developer Tools)

**Comment by Akopov4** [comment]
In developer tools I see an error: 
`mainThreadExtensionService.ts:107 Activating extension 'ms-python.vscode-python-envs' failed: Incompatible Python extension. Please update `ms-python.python` to version 2024.23 or later..
$onExtensionActivationError @ mainThreadExtensionService.ts:107`

**Comment by Akopov4** [comment]
How to update extension to check if it is still reproducible? @karthiknadig

**Comment by karthiknadig** [comment]
You can do this from the extensions view. Click on the switch to pre-release version button.
![Image](https://github.com/user-attachments/assets/be38af99-0671-437b-b5a9-c308c10deabf)
